ASM_FILES = [ 
    # Sadly, the order of these files matter, so be careful when changing it
    "asm/util.yaml",
    "asm/new_game.yaml",
    "asm/triggers.yaml",
    "asm/cutscenes.yaml",
    "asm/layouts.yaml",
    "asm/collect.yaml",
    "asm/location.yaml",
    # "asm/maku_tree.yaml",
    "asm/map_menu.yaml",
    # "asm/owl.yaml",
    "asm/progressives.yaml",
    "asm/quick_switch.yaml",
    "asm/animals.yaml",
    "asm/static_items.yaml",
    "asm/subscreen_1_improvement.yaml",
    "asm/multi.yaml",
    "asm/rings.yaml",
    "asm/misc.yaml",
    "asm/move_inventory.yaml",
    "asm/new_treasures.yaml",
    "asm/item_events.yaml",
    "asm/timeportals.yaml",
    "asm/boss_items.yaml",
    # "asm/business_scrubs.yaml",
    "asm/keysanity.yaml",
    # "asm/seed_tree.yaml",
    "asm/shops_handling.yaml",
    "asm/gfx.yaml",
    "asm/get_item_behavior.yaml",
    "asm/vars.yaml",
    "asm/text.yaml",
    "asm/remove_item_on_use.yaml",
    "asm/dungeon_shuffle.yaml",
    "asm/file_select_custom_string.yaml",
    # "asm/gasha_loot.yaml",
    "asm/impa_refill.yaml",
    "asm/combat_difficulty.yaml",
    "asm/tokay_market.yaml",
    "asm/compass_chimes.yaml",
    "asm/warp_to_start.yaml",
]
